from fastapi import FastAPI
import random

app = FastAPI()

# My Quotes
quotes = [
    "The only limit is your mind.",
    "Stay hungry, stay foolish.",
    "Knowledge is power.",
    "Time is money.",
    "Be yourself.",
    "Never give up.",
    "Success is a journey, not a destination.",
    "Dream big.",
    "Actions speak louder than words.",
    "Believe in yourself.",
    "Failure is success in progress.",
    "Hard work pays off.",
    "Practice makes perfect.",
    "Less is more.",
    "Carpe diem.",
    "Think different.",
    "Keep going.",
    "Stay positive.",
    "Progress over perfection.",
    "Do what you love.",
    "Love what you do.",
    "Discipline equals freedom.",
    "No pain no gain.",
    "Everything you can imagine is real.",
    "Make it happen.",
    "Small steps every day.",
    "Consistency is key.",
    "Don't stop learning.",
    "Be fearless.",
    "Embrace change.",
    "Create your own path.",
    "You are stronger than you think.",
    "Start where you are.",
    "Use what you have.",
    "Do your best.",
    "Stay humble.",
    "Work hard in silence.",
    "Let success make noise.",
    "The best is yet to come.",
    "Keep it simple.",
    "Focus on goals.",
    "Think positive.",
    "Stay strong.",
    "Never look back.",
    "Learn from mistakes.",
    "Believe and achieve.",
    "Make today count.",
    "One day or day one.",
    "Push yourself.",
    "Rise and grind.",
    "Nothing changes if nothing changes.",
    "Be the change.",
    "Act now.",
    "Stay curious.",
    "Knowledge grows when shared.",
    "Simplicity is the ultimate sophistication.",
    "Do more with less.",
    "Effort creates results.",
    "Winners never quit.",
    "Quitters never win.",
    "The future is now.",
    "Own your story.",
    "Live with purpose.",
    "Be unstoppable.",
    "Chase dreams.",
    "Build your future.",
    "Success requires sacrifice.",
    "Learn every day.",
    "Stay focused.",
    "Think long term.",
    "Short cuts make long delays.",
    "Quality over quantity.",
    "Work smarter.",
    "Stay disciplined.",
    "Be consistent.",
    "Keep learning.",
    "Improve daily.",
    "Trust the process.",
    "Enjoy the journey.",
    "Make it work.",
    "No excuses.",
    "Take responsibility.",
    "You got this.",
    "Be bold.",
    "Take risks.",
    "Learn to adapt.",
    "Stay motivated.",
    "Results matter.",
    "Dream it do it.",
    "Build discipline.",
    "Earn it.",
    "Go further.",
    "Never settle.",
    "Stay driven.",
    "Push limits.",
    "Aim high.",
    "Think big.",
    "Be relentless.",
    "Stay focused on goals.",
    "Make it happen daily.",
    "Every moment counts.",
    "Time waits for no one.",
    "Start today.",
    "Don't wait.",
    "Act with courage.",
    "Keep pushing forward.",
    "Growth takes time.",
    "Be patient.",
    "Stay consistent always.",
    "Hard times build strength.",
    "Pressure makes diamonds.",
    "You are capable.",
    "Believe in growth.",
    "Learn and improve.",
    "Keep striving.",
    "Turn pain into power.",
    "Stay resilient.",
    "Focus and win.",
    "Never quit on yourself.",
    "Build momentum.",
    "Keep evolving.",
    "Stay in motion.",
    "One step at a time.",
    "Progress matters.",
    "Keep your head up.",
    "Success is earned.",
    "Work for it.",
    "No limits.",
    "Think ahead.",
    "Stay sharp.",
    "Be prepared.",
    "Keep grinding.",
    "Make it real.",
    "Stay committed.",
    "Follow your vision.",
    "Create value.",
    "Add value.",
    "Lead yourself.",
    "Be consistent daily.",
    "Move forward.",
    "Don't look back.",
    "Stay determined.",
    "Keep faith in process.",
    "Make progress daily.",
    "Stay focused always.",
    "Work with purpose.",
    "Be intentional.",
    "Build habits.",
    "Master yourself.",
    "Success follows action."
]


@app.get("/")
def home():
    return {"message": "Motivation API is running!"}


@app.get("/quote")
def get_quote():
    return {
        "quote": random.choice(quotes)
    }
